language: csharp
solution: TextFileJoiner.sln
mono: latest
script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log